name: "📖 Documentation Improvement"
description: "Suggest improvements to docs, README, or examples"
title: "[Docs] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: "Documentation Type"
      description: "What type of documentation needs improvement?"
      options:
        - "README"
        - "Wiki"
        - "Rust Doc (inline comments)"
        - "Demo Application"
        - "Component API Docs"
        - "Example Code"
        - "Other"
    validations:
      required: true

  - type: input
    id: topic
    attributes:
      label: "Topic / Page"
      description: "Which specific topic or page needs improvement?"
      placeholder: "e.g., Getting Started, Button component, Toast demo"

  - type: textarea
    id: issue
    attributes:
      label: "Current Issue"
      description: "What's wrong or missing?"
      placeholder: "The installation instructions are outdated..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: "Suggested Improvement"
      description: "How would you improve it?"
      placeholder: "Add a section about pinning gpui version..."

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Any other context"
