name: "✨ Feature Request"
description: "Suggest a new component, widget, or feature"
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below to help us evaluate and implement it.

  - type: input
    id: feature-name
    attributes:
      label: "Feature Name"
      description: "What's the name of the feature?"
      placeholder: "e.g., DatePicker, Drag & Drop, ColorPicker"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "A clear and concise description of the feature"
      placeholder: "Describe the feature you would like to see..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation / Use Case"
      description: "Why do you need this feature? What's the use case?"
      placeholder: |
        I'm building a file manager and need a date picker to filter files by date...

  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Solution"
      description: "How do you envision this feature working?"
      placeholder: |
        A DatePicker component that:
        - Supports range selection
        - Has month/year navigation
        - Integrates with TextInput

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Any alternative solutions you've considered?"
      placeholder: "I tried using native HTML input type='date' but..."

  - type: textarea
    id: references
    attributes:
      label: "Reference Examples"
      description: "Any reference implementations or designs? (other UI libraries, mockups, etc.)"
      placeholder: |
        - Material UI DatePicker: https://mui.com/x/react-date-pickers/
        - Apple Calendar picker design

  - type: checkboxes
    id: component-type
    attributes:
      label: "Component Type"
      description: "What type of component is this?"
      options:
        - label: "Basic Component (Button, Input, etc.)"
        - label: "Advanced Widget (Tree, VirtualList, etc.)"
        - label: "Theme / Styling"
        - label: "Animation"
        - label: "Accessibility (ARIA, focus management)"
        - label: "i18n / Internationalization"
        - label: "Icons / Assets"
        - label: "Documentation"
        - label: "Other"

  - type: textarea
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this feature to you?"
      placeholder: "Must have / Nice to have / Low priority"

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add any other context here"
